[project]
name = "round-video-bot"
version = "2026.1.1"
description = "Telegram bot that converts videos and social media links into round video notes"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "aiogram[i18n]>=3.28.0",
    "aiogram_i18n>=1.4",
    "fluent_compiler==1.1",
    "python-dotenv>=1.2.0",
    "ffmpeg-python>=0.2.0",
    "Pillow>=12.0.0",
    "rlottie-python>=1.3.0",
    "yt-dlp>=2026.3.17",
    "sqlalchemy[asyncio]>=2.0.49",
    "asyncpg>=0.30.0",
    "alembic>=1.18.0",
    "greenlet==3.3.0",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy",
    "pytest",
    "pytest-asyncio",
]

[build-system]
requires = ["setuptools>=80.10.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]

[tool.mypy]
python_version = "3.10"
explicit_package_bases = true
exclude = ["^build/"]

[[tool.mypy.overrides]]
module = "ffmpeg.*"
ignore_missing_imports = true

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I"]
